spring.application.name=antici-ai-backend

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/antici_ai
spring.datasource.username=root
spring.datasource.password=root

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8081
jwt.secret=AnticiAIStudentAssistantSecretKey2026ForJWTAuthentication123456